spring.application.name=test
spring.datasource.url=jdbc:h2:mem:testdb
# ② H2 Console (超強力なデバッグツール) の有効化
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ③ テーブル自動作成
spring.jpa.hibernate.ddl-auto=update
# ④ 実行されたSQLのログ出力
spring.jpa.show-sql=true